# This file tests more or less everything related to a pull request. All
# in one big job. At the end, if all the testing passes, it proceeds
# to upload all the files that were built to our Dev environment.
# This way, if the tests passed, you'll be able to review the built
# pages on a public URL.

name: Validate

on: pull_request

permissions:
  # Compare two commits.
  contents: read

jobs:
  makeall:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Initialize environment
      run: |
        echo "Test"
        echo PR_NUMBER=${{ github.event.number }} >> ./mybuild/env
        echo GITHUB_SHA=${{ github.sha }} >> ./mybuild/env
    - name: Upload PR information to artifact
      uses: actions/upload-artifact@v4
      with:
          name: 'env'
          path: 'mybuild/'
